#+TITLE: Running Lab Data Service on Developement Environment
#+Author: VLEAD
#+Date: [2017-05-06 Fri]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../../org-templates/level-2.org
#+options: ^:nil

* Initial make
  Run make from =lab-data-service-dashboard= directory to
  build the application.  The code gets tangled. To install
  the dependencies and run the application, follow the steps
  listed below.

  #+BEGIN_EXAMPLE
  cp src/imp/runtime/config/config.org.sample src/imp/runtime/config/config.org
  make
  #+END_EXAMPLE


* Creation of Virtual Environment

  + Create Virtual Environemnt in the =lab-data-service-dashboard= directory
  #+BEGIN_EXAMPLE
  virtualenv venv
  #+END_EXAMPLE
  + Activate the Virtual Environment
  #+BEGIN_EXAMPLE
  source venv/bin/activate
  #+END_EXAMPLE

* Install Pre-requisite software
  Install the python development tools prior to installing
  the dependencies.
  #+BEGIN_EXAMPLE
  sudo su -
  apt-get install python-dev
  #+END_EXAMPLE

* Setting up dependencies
  Install all the dependencies for running the
  =lab-data-service-dashboard= applciation.  The =setup.py=
  script is in the =build/code/imp/deployment/= directory
  #+BEGIN_EXAMPLE
  cd build/code/imp/deployment/
  python setup.py install
  #+END_EXAMPLE

* Export PYTHONPATH
  Set PYTHONPATH variable and export it to access python modules. 
  #+BEGIN_EXAMPLE
  cd build/code/imp
  export PYTHONPATH=$(pwd) 
  #+END_EXAMPLE

  
* [[./google_oauth_configuration.org][Obtain Google OAuth Credentials]]

* Configure OAuth for Application
  Edit =src/runtime/config/config.py= to set =CLIENT_KEY= and
  =CLIENT_SECRET= that were obtained from the previous step. 
  
  This is necessary for the current application to use Google OAUTH service.

  #+BEGIN_EXAMPLE
    CLIENT_KEY = "<key>"
    CLIENT_SECRET = "<key>"
  #+END_EXAMPLE

* Run the application
  
  The application can now be run from the =build/code/runtime/rest/= directory
  #+BEGIN_EXAMPLE
  cd build/code/runtime/rest/
  python app.py
  #+END_EXAMPLE


* Access the application
  
  The application is accessed at =http://localhost:5000=
  

